package com.ud.audiolearning.administracion.ui;

import org.springframework.beans.factory.annotation.Autowired;
import org.vaadin.teemu.VaadinIcons;

import com.ud.audiolearning.administracion.service.AdministracionService;
import com.ud.audiolearning.api.anotaciones.UIComponent;
import com.ud.audiolearning.api.interfaces.AudioLearnUI;
import com.ud.audiolearning.api.domain.Denuncia;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Button;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

import ru.xpoft.vaadin.VaadinView;

@SuppressWarnings("serial")
@UIComponent
@VaadinView("Administracion/DenunciasProcesadas")
public class DenunciasProcesadas extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table table_1;
	@AutoGenerated
	private HorizontalLayout hl_cabecera;
	@AutoGenerated
	private Label l_titulo;
	private BeanItemContainer<Denuncia> BeanDenuncias;

	@Autowired
	AdministracionService administracionService;

	public DenunciasProcesadas() {

	}

	@Override
	public void enter(ViewChangeEvent event) {
		AudioLearnUI ui = (AudioLearnUI) UI.getCurrent();
		ui.getPrivateUI().getAreaContenido().setHeight("100%");
		buildMainLayout();
		setCompositionRoot(mainLayout);
		init();
		style();
	}

	private void init() {

		BeanDenuncias = new BeanItemContainer<>(Denuncia.class);
		BeanDenuncias.addNestedContainerBean("audio");
		BeanDenuncias.addNestedContainerBean("usuarioAtencion");
		table_1.setContainerDataSource(BeanDenuncias);

		table_1.addGeneratedColumn("ver", this::administracion);
		table_1.setVisibleColumns("id", "audio.titulo", "estado", "fechaApertura", "fechaCierre", "numeroDenuncias",
				"usuarioAtencion.nick", "detalleCierre");
		table_1.setColumnHeaders("ID DENUNCIA", "AUDIO", "ESTADO", "FECHA APERTURA", "FECHA CIERRE", "NUMERO DENUNCIAS",
				"USUARIO CIERRE", "OBSERVACIÓN");
		table_1.setSelectable(true);
		llenar(null);

	}

public Component administracion(Table source, Object itemId, Object columnId) {
		
		Denuncia denuncia = (Denuncia) itemId;
		
		Button b_verDetalle = new Button("Resolver");
		b_verDetalle.addClickListener(e-> verDetalles(denuncia));
		b_verDetalle.setIcon(VaadinIcons.EYE);
		b_verDetalle.addStyleName(ValoTheme.BUTTON_BORDERLESS_COLORED);
	
		return b_verDetalle;
	}
	private Object verDetalles(Denuncia denuncia) {
	
	return null;
}

	public void llenar(String valor) {

		BeanDenuncias.removeAllItems();
		BeanDenuncias.addAll(administracionService.denunciasProcesadas());

	}

	private void style() {

		l_titulo.addStyleName(ValoTheme.LABEL_COLORED);
		l_titulo.addStyleName(ValoTheme.LABEL_H2);
		l_titulo.addStyleName(ValoTheme.LABEL_BOLD);
		table_1.addStyleName("orangeHeader");
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setStyleName("contenido");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// hl_cabecera
		hl_cabecera = buildHl_cabecera();
		mainLayout.addComponent(hl_cabecera);
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("100.0%");
		table_1.setHeight("100.0%");
		mainLayout.addComponent(table_1);
		mainLayout.setExpandRatio(table_1, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHl_cabecera() {
		// common part: create layout
		hl_cabecera = new HorizontalLayout();
		hl_cabecera.setStyleName("cabeceraContenido");
		hl_cabecera.setImmediate(false);
		hl_cabecera.setWidth("100.0%");
		hl_cabecera.setHeight("-1px");
		hl_cabecera.setMargin(false);
		
		// l_titulo
		l_titulo = new Label();
		l_titulo.setImmediate(false);
		l_titulo.setWidth("-1px");
		l_titulo.setHeight("-1px");
		l_titulo.setValue("Denuncias Procesadas");
		hl_cabecera.addComponent(l_titulo);
		
		return hl_cabecera;
	}

}
