package com.ud.audiolearning.administracion.ui;

import java.util.function.Consumer;

import org.springframework.beans.factory.annotation.Autowired;
import org.vaadin.dialogs.ConfirmDialog;
import org.vaadin.teemu.VaadinIcons;

import com.ud.audiolearning.api.anotaciones.UIComponent;
import com.ud.audiolearning.api.domain.Parametrico;
import com.ud.audiolearning.api.service.ApiService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.themes.ValoTheme;

import ru.xpoft.vaadin.VaadinView;

@SuppressWarnings("serial")
@UIComponent
@VaadinView("Administracion/Parametricos")
public class Parametricos extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private Button b_removeDenuncia;
	@AutoGenerated
	private Button b_editarTipoDenuncia;
	@AutoGenerated
	private Button b_addTipoDenuncia;
	@AutoGenerated
	private Table tablaTiposDenuncia;
	@AutoGenerated
	private Panel panel_3;
	@AutoGenerated
	private VerticalLayout verticalLayout_5;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private Button b_removeIdiomas;
	@AutoGenerated
	private Button b_editarIdioma;
	@AutoGenerated
	private Button b_addIdioma;
	@AutoGenerated
	private Table tablaIdioma;
	@AutoGenerated
	private Panel panel_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button b_removePais;
	@AutoGenerated
	private Button b_editarPais;
	@AutoGenerated
	private Button b_addPais;
	@AutoGenerated
	private Table tablaPais;
	@AutoGenerated
	private Panel panel_4;
	@AutoGenerated
	private VerticalLayout verticalLayout_6;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button b_removeGenero;
	@AutoGenerated
	private Button b_editarGenero;
	@AutoGenerated
	private Button b_addGenero;
	@AutoGenerated
	private Table tablaGeneros;
	@AutoGenerated
	private HorizontalLayout hl_cabecera;
	@AutoGenerated
	private Label l_titulo;
	private BeanItemContainer<Parametrico> BICGeneros;

	@Autowired
	ApiService apiService;

	private BeanItemContainer<Parametrico> BICTiposDenuncia;
	private BeanItemContainer<Parametrico> BICIdiomas;
	private BeanItemContainer<Parametrico> BICPaises;

	private Parametrico selectedGenero;
	private Parametrico selectedIdioma;
	private Parametrico selectedTipoDenuncia;
	private Parametrico selectedPais;

	public Parametricos() {

	}

	@Override
	public void enter(ViewChangeEvent event) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		init();
		style();
	}

	private void init() {

		selectedGenero = new Parametrico();
		selectedIdioma = new Parametrico();
		selectedPais = new Parametrico();
		selectedTipoDenuncia = new Parametrico();

		iniciarTablas();
		cargarGeneros();
		cargarPaises();
		cargarIdiomas();
		cargarTiposDenuncia();

		tablaGeneros.addValueChangeListener(e -> cambioGenero(e));
		tablaIdioma.addValueChangeListener(e -> cambioIdioma(e));
		tablaTiposDenuncia.addValueChangeListener(e -> cambioTipoDenuncia(e));
		tablaPais.addValueChangeListener(e -> cambioPais(e));

		b_addGenero.addClickListener(e -> addParametrico("GENERO"));
		b_addIdioma.addClickListener(e -> addParametrico("IDIOMA"));
		b_addPais.addClickListener(e -> addParametrico("PAIS"));
		b_addTipoDenuncia.addClickListener(e -> addParametrico("TIPODENUNCIA"));

		b_removeDenuncia.addClickListener(e -> removerParametrico("TIPODENUNCIA"));
		b_removeGenero.addClickListener(e -> removerParametrico("GENERO"));
		b_removeIdiomas.addClickListener(e -> removerParametrico("IDIOMA"));
		b_removePais.addClickListener(e -> removerParametrico("PAIS"));

		b_editarTipoDenuncia.addClickListener(e -> editarParametrico("TIPODENUNCIA"));
		b_editarGenero.addClickListener(e -> editarParametrico("GENERO"));
		b_editarIdioma.addClickListener(e -> editarParametrico("IDIOMA"));
		b_editarPais.addClickListener(e -> editarParametrico("PAIS"));

	}

	public Consumer<String> consumerGeneros = (valor) -> cargarGeneros();
	public Consumer<String> consumerIdioma = (valor) -> cargarIdiomas();;
	public Consumer<String> consumerTipoDenuncia = (valor) -> cargarTiposDenuncia();
	public Consumer<String> consumerPais = (valor) -> cargarPaises();

	private void cambioPais(ValueChangeEvent e) {
		selectedPais = (Parametrico) e.getProperty().getValue();
	}

	private void cambioTipoDenuncia(ValueChangeEvent e) {
		selectedTipoDenuncia = (Parametrico) e.getProperty().getValue();
	}

	private void cambioIdioma(ValueChangeEvent e) {
		selectedIdioma = (Parametrico) e.getProperty().getValue();
	}

	private void cambioGenero(ValueChangeEvent e) {
		selectedGenero = (Parametrico) e.getProperty().getValue();
	}

	private void addParametrico(String Tipo) {

		Consumer<String> consumer = null;

		switch (Tipo) {
		case "IDIOMA":
			consumer = consumerIdioma;
			break;

		case "GENERO":
			consumer = consumerGeneros;

			break;
		case "TIPODENUNCIA":
			consumer = consumerTipoDenuncia;

			break;
		case "PAIS":
			consumer = consumerPais;
			break;
		}

		Window w = new Window();
		w.setContent(new ViewParametrico(Tipo, apiService, null, consumer));
		w.setWidth("-1px");
		w.setHeight("-1px");
		w.center();
		w.setModal(true);
		UI.getCurrent().addWindow(w);

	}

	private void removerParametrico(String Tipo) {

		ConfirmDialog.show(UI.getCurrent(), "Remover " + Tipo, "Esta seguro que desea remover el " + Tipo, "Remover",
				"No Remover", new ConfirmDialog.Listener() {

					public void onClose(ConfirmDialog dialog) {

						Parametrico removerParametrico = null;
						Consumer<String> consumer = null;
						switch (Tipo) {
						case "IDIOMA":
							removerParametrico = selectedIdioma;
							consumer = consumerIdioma;
							break;

						case "GENERO":
							removerParametrico = selectedGenero;
							consumer = consumerGeneros;

							break;
						case "TIPODENUNCIA":
							removerParametrico = selectedTipoDenuncia;
							consumer = consumerTipoDenuncia;
							break;
						case "PAIS":
							removerParametrico = selectedPais;
							consumer = consumerPais;
							break;
						}

					
						
						if (dialog.isConfirmed()) {
							apiService.removerParametrico(removerParametrico);
							consumer.accept(null);
							
							Notification n = new Notification("Correcto!", "Se ha eliminado con exito el registro",
									Type.HUMANIZED_MESSAGE);
							n.setDelayMsec(3600);
							n.show(UI.getCurrent().getPage());
						} else {
						}
					}
				});

	
	}

	private void editarParametrico(String Tipo) {

		Parametrico parametrico = null;
		Consumer<String> consumer = null;
		switch (Tipo) {
		case "IDIOMA":
			parametrico = selectedIdioma;
			consumer = consumerIdioma;
			break;

		case "GENERO":
			parametrico = selectedGenero;
			consumer = consumerGeneros;

			break;
		case "TIPODENUNCIA":
			parametrico = selectedTipoDenuncia;
			consumer = consumerTipoDenuncia;
			break;
		case "PAIS":
			parametrico = selectedPais;
			consumer = consumerPais;
			break;
		}


		Window w = new Window();
		w.setContent(new ViewParametrico(Tipo, apiService, parametrico, consumer));
		w.setWidth("-1px");
		w.setHeight("-1px");
		w.center();
		w.setModal(true);
		UI.getCurrent().addWindow(w);
	}

	private void iniciarTablas() {

		BICGeneros = new BeanItemContainer<Parametrico>(Parametrico.class);
		tablaGeneros.setContainerDataSource(BICGeneros);

		BICPaises = new BeanItemContainer<Parametrico>(Parametrico.class);
		tablaPais.setContainerDataSource(BICPaises);

		BICIdiomas = new BeanItemContainer<Parametrico>(Parametrico.class);
		tablaIdioma.setContainerDataSource(BICIdiomas);

		BICTiposDenuncia = new BeanItemContainer<Parametrico>(Parametrico.class);
		tablaTiposDenuncia.setContainerDataSource(BICTiposDenuncia);

	}

	private void cargarTiposDenuncia() {
		BICTiposDenuncia.removeAllItems();
		BICTiposDenuncia.addAll(apiService.findAllTiposDenuncia());
	}

	private void cargarIdiomas() {
		BICIdiomas.removeAllItems();
		BICIdiomas.addAll(apiService.selectItemsIdiomas());

	}

	private void cargarPaises() {
		BICPaises.removeAllItems();
		BICPaises.addAll(apiService.findAllPaises());

	}

	private void cargarGeneros() {
		BICGeneros.removeAllItems();
		BICGeneros.addAll(apiService.selectItemsGeneros());

	}

	private void style() {

		l_titulo.addStyleName(ValoTheme.LABEL_COLORED);
		l_titulo.addStyleName(ValoTheme.LABEL_H2);
		l_titulo.addStyleName(ValoTheme.LABEL_BOLD);

		tablaGeneros.addStyleName("tablaMarine");
		tablaIdioma.addStyleName("tablaMarine");
		tablaTiposDenuncia.addStyleName("tablaMarine");
		tablaPais.addStyleName("tablaMarine");

		b_addGenero.setIcon(VaadinIcons.PLUS);
		b_addGenero.setCaption("");
		b_addIdioma.setIcon(VaadinIcons.PLUS);
		b_addIdioma.setCaption("");
		b_addPais.setIcon(VaadinIcons.PLUS);
		b_addPais.setCaption("");
		b_addTipoDenuncia.setIcon(VaadinIcons.PLUS);
		b_addTipoDenuncia.setCaption("");

		b_removeDenuncia.setIcon(VaadinIcons.TRASH);
		b_removeDenuncia.setCaption("");
		b_removeGenero.setIcon(VaadinIcons.TRASH);
		b_removeGenero.setCaption("");
		b_removeIdiomas.setIcon(VaadinIcons.TRASH);
		b_removeIdiomas.setCaption("");
		b_removePais.setIcon(VaadinIcons.TRASH);
		b_removePais.setCaption("");

		b_editarTipoDenuncia.setIcon(VaadinIcons.EDIT);
		b_editarTipoDenuncia.setCaption("");
		b_editarGenero.setIcon(VaadinIcons.EDIT);
		b_editarGenero.setCaption("");
		b_editarIdioma.setIcon(VaadinIcons.EDIT);
		b_editarIdioma.setCaption("");
		b_editarPais.setIcon(VaadinIcons.EDIT);
		b_editarPais.setCaption("");

		b_addGenero.addStyleName(ValoTheme.BUTTON_FRIENDLY);
		b_addIdioma.addStyleName(ValoTheme.BUTTON_FRIENDLY);
		b_addPais.addStyleName(ValoTheme.BUTTON_FRIENDLY);
		b_addTipoDenuncia.addStyleName(ValoTheme.BUTTON_FRIENDLY);

		b_removeDenuncia.addStyleName(ValoTheme.BUTTON_DANGER);
		b_removeGenero.addStyleName(ValoTheme.BUTTON_DANGER);
		b_removeIdiomas.addStyleName(ValoTheme.BUTTON_DANGER);
		b_removePais.addStyleName(ValoTheme.BUTTON_DANGER);

		b_editarTipoDenuncia.addStyleName(ValoTheme.BUTTON_PRIMARY);
		b_editarGenero.addStyleName(ValoTheme.BUTTON_PRIMARY);
		b_editarIdioma.addStyleName(ValoTheme.BUTTON_PRIMARY);
		b_editarPais.addStyleName(ValoTheme.BUTTON_PRIMARY);

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setStyleName("contenido");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");

		// hl_cabecera
		hl_cabecera = buildHl_cabecera();
		mainLayout.addComponent(hl_cabecera);

		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1);
		mainLayout.setExpandRatio(gridLayout_1, 1.0f);

		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHl_cabecera() {
		// common part: create layout
		hl_cabecera = new HorizontalLayout();
		hl_cabecera.setStyleName("cabeceraContenido");
		hl_cabecera.setImmediate(false);
		hl_cabecera.setWidth("100.0%");
		hl_cabecera.setHeight("-1px");
		hl_cabecera.setMargin(false);

		// l_titulo
		l_titulo = new Label();
		l_titulo.setImmediate(false);
		l_titulo.setWidth("-1px");
		l_titulo.setHeight("-1px");
		l_titulo.setValue("Parametrizaciones");
		hl_cabecera.addComponent(l_titulo);

		return hl_cabecera;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setColumns(2);
		gridLayout_1.setRows(3);

		// panel_4
		panel_4 = buildPanel_4();
		gridLayout_1.addComponent(panel_4, 0, 0);
		gridLayout_1.setComponentAlignment(panel_4, new Alignment(48));

		// panel_2
		panel_2 = buildPanel_2();
		gridLayout_1.addComponent(panel_2, 1, 0);
		gridLayout_1.setComponentAlignment(panel_2, new Alignment(48));

		// panel_3
		panel_3 = buildPanel_3();
		gridLayout_1.addComponent(panel_3, 0, 2);
		gridLayout_1.setComponentAlignment(panel_3, new Alignment(48));

		// panel_1
		panel_1 = buildPanel_1();
		gridLayout_1.addComponent(panel_1, 1, 2);
		gridLayout_1.setComponentAlignment(panel_1, new Alignment(48));

		return gridLayout_1;
	}

	@AutoGenerated
	private Panel buildPanel_4() {
		// common part: create layout
		panel_4 = new Panel();
		panel_4.setCaption("Generos");
		panel_4.setImmediate(false);
		panel_4.setWidth("90.0%");
		panel_4.setHeight("400px");

		// verticalLayout_6
		verticalLayout_6 = buildVerticalLayout_6();
		panel_4.setContent(verticalLayout_6);

		return panel_4;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_6() {
		// common part: create layout
		verticalLayout_6 = new VerticalLayout();
		verticalLayout_6.setImmediate(false);
		verticalLayout_6.setWidth("100.0%");
		verticalLayout_6.setHeight("100.0%");
		verticalLayout_6.setMargin(true);
		verticalLayout_6.setSpacing(true);

		// tablaGeneros
		tablaGeneros = new Table();
		tablaGeneros.setImmediate(true);
		tablaGeneros.setWidth("100.0%");
		tablaGeneros.setHeight("100.0%");
		verticalLayout_6.addComponent(tablaGeneros);
		verticalLayout_6.setExpandRatio(tablaGeneros, 1.0f);

		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_6.addComponent(horizontalLayout_1);
		verticalLayout_6.setComponentAlignment(horizontalLayout_1, new Alignment(48));

		return verticalLayout_6;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);

		// b_addGenero
		b_addGenero = new Button();
		b_addGenero.setCaption("Button");
		b_addGenero.setImmediate(true);
		b_addGenero.setWidth("-1px");
		b_addGenero.setHeight("-1px");
		horizontalLayout_1.addComponent(b_addGenero);

		// b_editarGenero
		b_editarGenero = new Button();
		b_editarGenero.setCaption("Button");
		b_editarGenero.setImmediate(true);
		b_editarGenero.setWidth("-1px");
		b_editarGenero.setHeight("-1px");
		horizontalLayout_1.addComponent(b_editarGenero);

		// b_removeGenero
		b_removeGenero = new Button();
		b_removeGenero.setCaption("Button");
		b_removeGenero.setImmediate(true);
		b_removeGenero.setWidth("-1px");
		b_removeGenero.setHeight("-1px");
		horizontalLayout_1.addComponent(b_removeGenero);

		return horizontalLayout_1;
	}

	@AutoGenerated
	private Panel buildPanel_2() {
		// common part: create layout
		panel_2 = new Panel();
		panel_2.setCaption("Países");
		panel_2.setImmediate(false);
		panel_2.setWidth("90.0%");
		panel_2.setHeight("400px");

		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		panel_2.setContent(verticalLayout_4);

		return panel_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("100.0%");
		verticalLayout_4.setHeight("100.0%");
		verticalLayout_4.setMargin(true);
		verticalLayout_4.setSpacing(true);

		// tablaPais
		tablaPais = new Table();
		tablaPais.setImmediate(true);
		tablaPais.setWidth("100.0%");
		tablaPais.setHeight("100.0%");
		verticalLayout_4.addComponent(tablaPais);
		verticalLayout_4.setExpandRatio(tablaPais, 1.0f);

		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		verticalLayout_4.addComponent(horizontalLayout_2);
		verticalLayout_4.setComponentAlignment(horizontalLayout_2, new Alignment(48));

		return verticalLayout_4;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);

		// b_addPais
		b_addPais = new Button();
		b_addPais.setCaption("Button");
		b_addPais.setImmediate(true);
		b_addPais.setWidth("-1px");
		b_addPais.setHeight("-1px");
		horizontalLayout_2.addComponent(b_addPais);

		// b_editarPais
		b_editarPais = new Button();
		b_editarPais.setCaption("Button");
		b_editarPais.setImmediate(true);
		b_editarPais.setWidth("-1px");
		b_editarPais.setHeight("-1px");
		horizontalLayout_2.addComponent(b_editarPais);

		// b_removePais
		b_removePais = new Button();
		b_removePais.setCaption("Button");
		b_removePais.setImmediate(true);
		b_removePais.setWidth("-1px");
		b_removePais.setHeight("-1px");
		horizontalLayout_2.addComponent(b_removePais);

		return horizontalLayout_2;
	}

	@AutoGenerated
	private Panel buildPanel_3() {
		// common part: create layout
		panel_3 = new Panel();
		panel_3.setCaption("Idiomas");
		panel_3.setImmediate(false);
		panel_3.setWidth("90.0%");
		panel_3.setHeight("400px");

		// verticalLayout_5
		verticalLayout_5 = buildVerticalLayout_5();
		panel_3.setContent(verticalLayout_5);

		return panel_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_5() {
		// common part: create layout
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(false);
		verticalLayout_5.setWidth("100.0%");
		verticalLayout_5.setHeight("100.0%");
		verticalLayout_5.setMargin(true);
		verticalLayout_5.setSpacing(true);

		// tablaIdioma
		tablaIdioma = new Table();
		tablaIdioma.setImmediate(true);
		tablaIdioma.setWidth("100.0%");
		tablaIdioma.setHeight("100.0%");
		verticalLayout_5.addComponent(tablaIdioma);
		verticalLayout_5.setExpandRatio(tablaIdioma, 1.0f);

		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		verticalLayout_5.addComponent(horizontalLayout_4);
		verticalLayout_5.setComponentAlignment(horizontalLayout_4, new Alignment(48));

		return verticalLayout_5;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("-1px");
		horizontalLayout_4.setHeight("-1px");
		horizontalLayout_4.setMargin(false);
		horizontalLayout_4.setSpacing(true);

		// b_addIdioma
		b_addIdioma = new Button();
		b_addIdioma.setCaption("Button");
		b_addIdioma.setImmediate(true);
		b_addIdioma.setWidth("-1px");
		b_addIdioma.setHeight("-1px");
		horizontalLayout_4.addComponent(b_addIdioma);

		// b_editarIdioma
		b_editarIdioma = new Button();
		b_editarIdioma.setCaption("Button");
		b_editarIdioma.setImmediate(true);
		b_editarIdioma.setWidth("-1px");
		b_editarIdioma.setHeight("-1px");
		horizontalLayout_4.addComponent(b_editarIdioma);

		// b_removeIdiomas
		b_removeIdiomas = new Button();
		b_removeIdiomas.setCaption("Button");
		b_removeIdiomas.setImmediate(true);
		b_removeIdiomas.setWidth("-1px");
		b_removeIdiomas.setHeight("-1px");
		horizontalLayout_4.addComponent(b_removeIdiomas);

		return horizontalLayout_4;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setCaption("Tipos de Denuncia");
		panel_1.setImmediate(false);
		panel_1.setWidth("90.0%");
		panel_1.setHeight("400px");

		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		panel_1.setContent(verticalLayout_3);

		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(true);
		verticalLayout_3.setSpacing(true);

		// tablaTiposDenuncia
		tablaTiposDenuncia = new Table();
		tablaTiposDenuncia.setImmediate(true);
		tablaTiposDenuncia.setWidth("100.0%");
		tablaTiposDenuncia.setHeight("100.0%");
		verticalLayout_3.addComponent(tablaTiposDenuncia);
		verticalLayout_3.setExpandRatio(tablaTiposDenuncia, 1.0f);

		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		verticalLayout_3.addComponent(horizontalLayout_3);
		verticalLayout_3.setComponentAlignment(horizontalLayout_3, new Alignment(48));

		return verticalLayout_3;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		horizontalLayout_3.setSpacing(true);

		// b_addTipoDenuncia
		b_addTipoDenuncia = new Button();
		b_addTipoDenuncia.setCaption("Button");
		b_addTipoDenuncia.setImmediate(true);
		b_addTipoDenuncia.setWidth("-1px");
		b_addTipoDenuncia.setHeight("-1px");
		horizontalLayout_3.addComponent(b_addTipoDenuncia);

		// b_editarTipoDenuncia
		b_editarTipoDenuncia = new Button();
		b_editarTipoDenuncia.setCaption("Button");
		b_editarTipoDenuncia.setImmediate(true);
		b_editarTipoDenuncia.setWidth("-1px");
		b_editarTipoDenuncia.setHeight("-1px");
		horizontalLayout_3.addComponent(b_editarTipoDenuncia);

		// b_removeDenuncia
		b_removeDenuncia = new Button();
		b_removeDenuncia.setCaption("Button");
		b_removeDenuncia.setImmediate(true);
		b_removeDenuncia.setWidth("-1px");
		b_removeDenuncia.setHeight("-1px");
		horizontalLayout_3.addComponent(b_removeDenuncia);

		return horizontalLayout_3;
	}

}
