package com.ud.audiolearning.administracion.ui;

import org.springframework.beans.factory.annotation.Autowired;

import com.ud.audiolearning.api.anotaciones.UIComponent;
import com.ud.audiolearning.api.domain.Parametrico;
import com.ud.audiolearning.api.service.ApiService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.themes.ValoTheme;

import ru.xpoft.vaadin.VaadinView;

@SuppressWarnings("serial")
@UIComponent
@VaadinView("Administracion/Parametricos")
public class Parametricos extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private Button button_6;
	@AutoGenerated
	private Button button_5;
	@AutoGenerated
	private Table tablaTiposDenuncia;
	@AutoGenerated
	private Panel panel_3;
	@AutoGenerated
	private VerticalLayout verticalLayout_5;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private Button button_8;
	@AutoGenerated
	private Button button_7;
	@AutoGenerated
	private Table tablaIdioma;
	@AutoGenerated
	private Panel panel_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button button_4;
	@AutoGenerated
	private Button button_3;
	@AutoGenerated
	private Table tablaPais;
	@AutoGenerated
	private Panel panel_4;
	@AutoGenerated
	private VerticalLayout verticalLayout_6;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private Table tablaGeneros;
	@AutoGenerated
	private HorizontalLayout hl_cabecera;
	@AutoGenerated
	private Label l_titulo;
	private BeanItemContainer<Parametrico> BICGeneros;

	@Autowired
	ApiService apiService;
	private BeanItemContainer<Parametrico> BICTiposDenuncia;
	private BeanItemContainer<Parametrico> BICIdiomas;
	private BeanItemContainer<Parametrico> BICPaices;

	public Parametricos() {

	}

	@Override
	public void enter(ViewChangeEvent event) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		init();
		style();
	}

	private void init() {

		iniciarTablas();
		cargarGeneros();
		cargarPaices();
		cargarIdiomas();
		cargarTiposDenuncia();
		
		button_1.addClickListener(e-> addGenero());
		
		
		Window viewParametrico = new ViewParametrico();
	
		viewParametrico.setWidth("-1px");
		viewParametrico.setHeight("-1px");
		viewParametrico.center();
		viewParametrico.setModal(true);
		UI.getCurrent().addWindow(viewParametrico);

	}

	private void addGenero() {
		
		
		
	}

	private void iniciarTablas() {

		BICGeneros = new BeanItemContainer<Parametrico>(Parametrico.class);
		tablaGeneros.setContainerDataSource(BICGeneros);

		BICPaices = new BeanItemContainer<Parametrico>(Parametrico.class);
		tablaPais.setContainerDataSource(BICPaices);

		BICIdiomas = new BeanItemContainer<Parametrico>(Parametrico.class);
		tablaIdioma.setContainerDataSource(BICIdiomas);

		BICTiposDenuncia = new BeanItemContainer<Parametrico>(Parametrico.class);
		tablaTiposDenuncia.setContainerDataSource(BICTiposDenuncia);

	}

	private void cargarTiposDenuncia() {
		BICTiposDenuncia.removeAllItems();
		BICTiposDenuncia.addAll(apiService.findAllTiposDenuncia());
	}

	private void cargarIdiomas() {
		BICIdiomas.removeAllItems();
		BICIdiomas.addAll(apiService.selectItemsIdiomas());

	}

	private void cargarPaices() {
		BICPaices.removeAllItems();
		BICPaices.addAll(apiService.findAllPaices());

	}

	private void cargarGeneros() {
		BICGeneros.removeAllItems();
		BICGeneros.addAll(apiService.selectItemsGeneros());

	}

	private void style() {

		l_titulo.addStyleName(ValoTheme.LABEL_COLORED);
		l_titulo.addStyleName(ValoTheme.LABEL_H2);
		l_titulo.addStyleName(ValoTheme.LABEL_BOLD);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setStyleName("contenido");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// hl_cabecera
		hl_cabecera = buildHl_cabecera();
		mainLayout.addComponent(hl_cabecera);
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1);
		mainLayout.setExpandRatio(gridLayout_1, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHl_cabecera() {
		// common part: create layout
		hl_cabecera = new HorizontalLayout();
		hl_cabecera.setStyleName("cabeceraContenido");
		hl_cabecera.setImmediate(false);
		hl_cabecera.setWidth("100.0%");
		hl_cabecera.setHeight("-1px");
		hl_cabecera.setMargin(false);
		
		// l_titulo
		l_titulo = new Label();
		l_titulo.setImmediate(false);
		l_titulo.setWidth("-1px");
		l_titulo.setHeight("-1px");
		l_titulo.setValue("Parametrizaciones");
		hl_cabecera.addComponent(l_titulo);
		
		return hl_cabecera;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setColumns(2);
		gridLayout_1.setRows(3);
		
		// panel_4
		panel_4 = buildPanel_4();
		gridLayout_1.addComponent(panel_4, 0, 0);
		gridLayout_1.setComponentAlignment(panel_4, new Alignment(48));
		
		// panel_2
		panel_2 = buildPanel_2();
		gridLayout_1.addComponent(panel_2, 1, 0);
		gridLayout_1.setComponentAlignment(panel_2, new Alignment(48));
		
		// panel_3
		panel_3 = buildPanel_3();
		gridLayout_1.addComponent(panel_3, 0, 2);
		gridLayout_1.setComponentAlignment(panel_3, new Alignment(48));
		
		// panel_1
		panel_1 = buildPanel_1();
		gridLayout_1.addComponent(panel_1, 1, 2);
		gridLayout_1.setComponentAlignment(panel_1, new Alignment(48));
		
		return gridLayout_1;
	}

	@AutoGenerated
	private Panel buildPanel_4() {
		// common part: create layout
		panel_4 = new Panel();
		panel_4.setCaption("Generos");
		panel_4.setImmediate(false);
		panel_4.setWidth("90.0%");
		panel_4.setHeight("400px");
		
		// verticalLayout_6
		verticalLayout_6 = buildVerticalLayout_6();
		panel_4.setContent(verticalLayout_6);
		
		return panel_4;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_6() {
		// common part: create layout
		verticalLayout_6 = new VerticalLayout();
		verticalLayout_6.setImmediate(false);
		verticalLayout_6.setWidth("100.0%");
		verticalLayout_6.setHeight("100.0%");
		verticalLayout_6.setMargin(true);
		verticalLayout_6.setSpacing(true);
		
		// tablaGeneros
		tablaGeneros = new Table();
		tablaGeneros.setImmediate(false);
		tablaGeneros.setWidth("100.0%");
		tablaGeneros.setHeight("100.0%");
		verticalLayout_6.addComponent(tablaGeneros);
		verticalLayout_6.setExpandRatio(tablaGeneros, 1.0f);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_6.addComponent(horizontalLayout_1);
		verticalLayout_6.setComponentAlignment(horizontalLayout_1, new Alignment(48));
		
		return verticalLayout_6;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Add");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		horizontalLayout_1.addComponent(button_1);
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Button");
		button_2.setImmediate(true);
		button_2.setWidth("-1px");
		button_2.setHeight("-1px");
		horizontalLayout_1.addComponent(button_2);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private Panel buildPanel_2() {
		// common part: create layout
		panel_2 = new Panel();
		panel_2.setCaption("Paices");
		panel_2.setImmediate(false);
		panel_2.setWidth("90.0%");
		panel_2.setHeight("400px");
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		panel_2.setContent(verticalLayout_4);
		
		return panel_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("100.0%");
		verticalLayout_4.setHeight("100.0%");
		verticalLayout_4.setMargin(true);
		verticalLayout_4.setSpacing(true);
		
		// tablaPais
		tablaPais = new Table();
		tablaPais.setImmediate(false);
		tablaPais.setWidth("100.0%");
		tablaPais.setHeight("100.0%");
		verticalLayout_4.addComponent(tablaPais);
		verticalLayout_4.setExpandRatio(tablaPais, 1.0f);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		verticalLayout_4.addComponent(horizontalLayout_2);
		verticalLayout_4.setComponentAlignment(horizontalLayout_2, new Alignment(48));
		
		return verticalLayout_4;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// button_3
		button_3 = new Button();
		button_3.setCaption("Button");
		button_3.setImmediate(true);
		button_3.setWidth("-1px");
		button_3.setHeight("-1px");
		horizontalLayout_2.addComponent(button_3);
		
		// button_4
		button_4 = new Button();
		button_4.setCaption("Button");
		button_4.setImmediate(true);
		button_4.setWidth("-1px");
		button_4.setHeight("-1px");
		horizontalLayout_2.addComponent(button_4);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private Panel buildPanel_3() {
		// common part: create layout
		panel_3 = new Panel();
		panel_3.setCaption("Idiomas");
		panel_3.setImmediate(false);
		panel_3.setWidth("90.0%");
		panel_3.setHeight("400px");
		
		// verticalLayout_5
		verticalLayout_5 = buildVerticalLayout_5();
		panel_3.setContent(verticalLayout_5);
		
		return panel_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_5() {
		// common part: create layout
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(false);
		verticalLayout_5.setWidth("100.0%");
		verticalLayout_5.setHeight("100.0%");
		verticalLayout_5.setMargin(true);
		verticalLayout_5.setSpacing(true);
		
		// tablaIdioma
		tablaIdioma = new Table();
		tablaIdioma.setImmediate(false);
		tablaIdioma.setWidth("100.0%");
		tablaIdioma.setHeight("100.0%");
		verticalLayout_5.addComponent(tablaIdioma);
		verticalLayout_5.setExpandRatio(tablaIdioma, 1.0f);
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		verticalLayout_5.addComponent(horizontalLayout_4);
		verticalLayout_5.setComponentAlignment(horizontalLayout_4, new Alignment(48));
		
		return verticalLayout_5;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("-1px");
		horizontalLayout_4.setHeight("-1px");
		horizontalLayout_4.setMargin(false);
		horizontalLayout_4.setSpacing(true);
		
		// button_7
		button_7 = new Button();
		button_7.setCaption("Button");
		button_7.setImmediate(true);
		button_7.setWidth("-1px");
		button_7.setHeight("-1px");
		horizontalLayout_4.addComponent(button_7);
		
		// button_8
		button_8 = new Button();
		button_8.setCaption("Button");
		button_8.setImmediate(true);
		button_8.setWidth("-1px");
		button_8.setHeight("-1px");
		horizontalLayout_4.addComponent(button_8);
		
		return horizontalLayout_4;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setCaption("Tipos de Denuncia");
		panel_1.setImmediate(false);
		panel_1.setWidth("90.0%");
		panel_1.setHeight("400px");
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		panel_1.setContent(verticalLayout_3);
		
		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(true);
		verticalLayout_3.setSpacing(true);
		
		// tablaTiposDenuncia
		tablaTiposDenuncia = new Table();
		tablaTiposDenuncia.setImmediate(false);
		tablaTiposDenuncia.setWidth("100.0%");
		tablaTiposDenuncia.setHeight("100.0%");
		verticalLayout_3.addComponent(tablaTiposDenuncia);
		verticalLayout_3.setExpandRatio(tablaTiposDenuncia, 1.0f);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		verticalLayout_3.addComponent(horizontalLayout_3);
		verticalLayout_3.setComponentAlignment(horizontalLayout_3, new Alignment(48));
		
		return verticalLayout_3;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		horizontalLayout_3.setSpacing(true);
		
		// button_5
		button_5 = new Button();
		button_5.setCaption("Button");
		button_5.setImmediate(true);
		button_5.setWidth("-1px");
		button_5.setHeight("-1px");
		horizontalLayout_3.addComponent(button_5);
		
		// button_6
		button_6 = new Button();
		button_6.setCaption("Button");
		button_6.setImmediate(true);
		button_6.setWidth("-1px");
		button_6.setHeight("-1px");
		horizontalLayout_3.addComponent(button_6);
		
		return horizontalLayout_3;
	}

}
