package com.ud.audiolearning.administracion.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Grid;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

@SuppressWarnings("serial")
public class ViewRol extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button b_editarRol;
	@AutoGenerated
	private Button b_crearRol;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Panel panel_3;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Label l_permisos;
	@AutoGenerated
	private TextArea textArea_1;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label l_titulo;
	public ViewRol() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		init();
		style();
	}

	
	
	private void init(){
		
		gridLayout_1.setColumnExpandRatio(1, 1.0f);
		
		
		Grid General = new Grid();

		Grid acceso = new Grid();
	}
	
	
private void style(){
		
		l_permisos.addStyleName(ValoTheme.LABEL_BOLD);
		l_permisos.addStyleName(ValoTheme.LABEL_H2);
		l_permisos.addStyleName(ValoTheme.LABEL_COLORED);
		
		l_titulo.addStyleName(ValoTheme.LABEL_BOLD);
		l_titulo.addStyleName(ValoTheme.LABEL_H2);
		l_titulo.addStyleName(ValoTheme.LABEL_COLORED);
		
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// l_titulo
		l_titulo = new Label();
		l_titulo.setStyleName("mih2");
		l_titulo.setImmediate(false);
		l_titulo.setWidth("-1px");
		l_titulo.setHeight("-1px");
		l_titulo.setValue("Titulo");
		mainLayout.addComponent(l_titulo);
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// b_crearRol
		b_crearRol = new Button();
		b_crearRol.setCaption("Crear");
		b_crearRol.setImmediate(true);
		b_crearRol.setWidth("-1px");
		b_crearRol.setHeight("-1px");
		mainLayout.addComponent(b_crearRol);
		mainLayout.setComponentAlignment(b_crearRol, new Alignment(48));
		
		// b_editarRol
		b_editarRol = new Button();
		b_editarRol.setCaption("Editar");
		b_editarRol.setImmediate(true);
		b_editarRol.setWidth("-1px");
		b_editarRol.setHeight("-1px");
		mainLayout.addComponent(b_editarRol);
		mainLayout.setComponentAlignment(b_editarRol, new Alignment(48));
		
		return mainLayout;
	}



	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setColumns(2);
		gridLayout_1.setRows(3);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Nombre Rol");
		gridLayout_1.addComponent(label_3, 0, 0);
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("100.0%");
		textField_1.setHeight("-1px");
		gridLayout_1.addComponent(textField_1, 1, 0);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Descripción");
		gridLayout_1.addComponent(label_2, 0, 1);
		
		// textArea_1
		textArea_1 = new TextArea();
		textArea_1.setImmediate(false);
		textArea_1.setWidth("100.0%");
		textArea_1.setHeight("-1px");
		gridLayout_1.addComponent(textArea_1, 1, 1);
		
		// l_permisos
		l_permisos = new Label();
		l_permisos.setStyleName("mih2");
		l_permisos.setImmediate(false);
		l_permisos.setWidth("-1px");
		l_permisos.setHeight("-1px");
		l_permisos.setValue("Permisos");
		gridLayout_1.addComponent(l_permisos, 0, 2);
		
		return gridLayout_1;
	}



	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// panel_1
		panel_1 = buildPanel_1();
		horizontalLayout_1.addComponent(panel_1);
		
		// panel_3
		panel_3 = buildPanel_3();
		horizontalLayout_1.addComponent(panel_3);
		
		return horizontalLayout_1;
	}



	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setCaption("Acceso");
		panel_1.setImmediate(false);
		panel_1.setWidth("250px");
		panel_1.setHeight("180px");
		
		// verticalLayout_2
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);
		panel_1.setContent(verticalLayout_2);
		
		return panel_1;
	}



	@AutoGenerated
	private Panel buildPanel_3() {
		// common part: create layout
		panel_3 = new Panel();
		panel_3.setCaption("General");
		panel_3.setImmediate(false);
		panel_3.setWidth("250px");
		panel_3.setHeight("180px");
		
		// verticalLayout_4
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("100.0%");
		verticalLayout_4.setHeight("100.0%");
		verticalLayout_4.setMargin(false);
		panel_3.setContent(verticalLayout_4);
		
		return panel_3;
	}

}
