package com.ud.audiolearning.administracion.ui;

import org.vaadin.teemu.VaadinIcons;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.FontAwesome;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.themes.ValoTheme;

public class ViewParametrico extends Window {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Button b_crearParametrico;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private ComboBox comboBox_1;
	@AutoGenerated
	private Label label_5;
	@AutoGenerated
	private TextField textField_2;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private Label label_2;

	public ViewParametrico() {
		buildMainLayout();
		setContent(mainLayout);

		init();
		style();
		
	}
	
	private void init(){
		 
		Embedded imagen = new Embedded();
		imagen.setHeight("128px");
		imagen.setWidth("128px");
		imagen.setSource(new ThemeResource("img/gear-icon.png"));
		mainLayout.addComponent(imagen, 0);
		mainLayout.setComponentAlignment(imagen, Alignment.MIDDLE_CENTER);
		
	}
	
	
	private void style(){
		
		b_crearParametrico.addStyleName(ValoTheme.BUTTON_PRIMARY);
		b_crearParametrico.setIcon(FontAwesome.SAVE);
		
	}
	

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("-1px");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(false);
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		verticalLayout_1.addComponent(gridLayout_1);
		
		// b_crearParametrico
		b_crearParametrico = new Button();
		b_crearParametrico.setCaption("Crear");
		b_crearParametrico.setImmediate(true);
		b_crearParametrico.setWidth("-1px");
		b_crearParametrico.setHeight("-1px");
		verticalLayout_1.addComponent(b_crearParametrico);
		verticalLayout_1.setComponentAlignment(b_crearParametrico, new Alignment(48));
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("-1px");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(true);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setColumns(2);
		gridLayout_1.setRows(3);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Label");
		gridLayout_1.addComponent(label_2, 0, 0);
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		gridLayout_1.addComponent(textField_1, 1, 0);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Label");
		gridLayout_1.addComponent(label_3, 0, 1);
		
		// textField_2
		textField_2 = new TextField();
		textField_2.setImmediate(false);
		textField_2.setWidth("-1px");
		textField_2.setHeight("-1px");
		gridLayout_1.addComponent(textField_2, 1, 1);
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("Label");
		gridLayout_1.addComponent(label_5, 0, 2);
		
		// comboBox_1
		comboBox_1 = new ComboBox();
		comboBox_1.setImmediate(false);
		comboBox_1.setWidth("-1px");
		comboBox_1.setHeight("-1px");
		gridLayout_1.addComponent(comboBox_1, 1, 2);
		
		return gridLayout_1;
	}

}
