package com.ud.audiolearning.administracion.ui;

import java.util.ArrayList;
import java.util.List;

import com.ud.audiolearning.administracion.service.AdministracionService;
import com.ud.audiolearning.api.domain.ALMenuItem;
import com.ud.audiolearning.api.domain.Parametrico;
import com.ud.audiolearning.api.domain.Rol;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.util.BeanItem;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Grid.SelectionMode;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

@SuppressWarnings("serial")
public class ViewRol extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button b_editarRol;
	@AutoGenerated
	private Button b_crearRol;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Panel panel_3;
	@AutoGenerated
	private VerticalLayout vl_general;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout vl_acceso;
	@AutoGenerated
	private Label l_permisos;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private TextArea ta_descripcion;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private TextField tf_nombreRol;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label l_titulo;
	AdministracionService administracionService;
	private BeanItemContainer<ALMenuItem> BICMenu;
	private Grid acceso;
	private Grid General;
	private Rol rol;
	private FieldGroup binder;
	private BeanItem<Rol> BIRol;
	private BeanItemContainer<String> BICGeneral;

	public ViewRol(Rol rol, AdministracionService administracionService) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		this.rol = rol;
		this.administracionService = administracionService;

		init();
		style();
	}

	private void init() {

		gridLayout_1.setColumnExpandRatio(1, 1.0f);

		llenarImputs();

		binder = new FieldGroup();
		binder.bind(ta_descripcion, "descripcion");
		binder.bind(tf_nombreRol, "nombre");

		b_crearRol.setVisible(false);
		b_editarRol.setVisible(false);

		if (this.rol == null) {
			this.rol = new Rol();
			l_titulo.setValue("Crear Nuevo Rol");
			b_crearRol.setVisible(true);
		} else {
			l_titulo.setValue("Editar Rol " + this.rol.getNombre());
			b_editarRol.setVisible(true);

			this.rol.getMenuItems().forEach(item -> acceso.select(item));
		

		}

		BIRol = new BeanItem<Rol>(this.rol);
		binder.setItemDataSource(BIRol);

	}

	private void llenarImputs() {

		tf_nombreRol.setNullRepresentation("");
		ta_descripcion.setNullRepresentation("");

		acceso = new Grid();
		acceso.setSelectionMode(SelectionMode.MULTI);

		BICMenu = new BeanItemContainer<ALMenuItem>(ALMenuItem.class);
		BICMenu.addAll(administracionService.consultarMenuItems());
		acceso.setContainerDataSource(BICMenu);

		acceso.removeColumn("id");
		acceso.removeColumn("url");
		acceso.removeColumn("estado");
		acceso.removeColumn("navegable");
		acceso.removeColumn("items");

		vl_acceso.addComponent(acceso);
		acceso.setHeight("200px");

		General = new Grid();
		BICGeneral = new BeanItemContainer<>(String.class);
		
		List<String> commonUrl = new ArrayList<String>();
		commonUrl.add("perfilUsuario");
		commonUrl.add("reproductor");
		commonUrl.add("preferencias");
		commonUrl.add("editarAudio");
		commonUrl.add("Busqueda");
		
		BICGeneral.addAll(commonUrl);
		
		General.setSelectionMode(SelectionMode.MULTI);

		//General.setContainerDataSource(BICGeneral);
		
		General.addColumn("valor",String.class);
	
		General.addRow("perfilUsuario");
		General.addRow("reproductor");
		General.addRow("preferencias");
		General.addRow("editarAudio");
		General.addRow("Busqueda");
		
		
		
		vl_general.addComponent(General);
		General.setHeight("200px");

	}

	private void style() {

		l_permisos.addStyleName(ValoTheme.LABEL_BOLD);
		l_permisos.addStyleName(ValoTheme.LABEL_H2);
		l_permisos.addStyleName(ValoTheme.LABEL_COLORED);

		l_titulo.addStyleName(ValoTheme.LABEL_BOLD);
		l_titulo.addStyleName(ValoTheme.LABEL_H2);
		l_titulo.addStyleName(ValoTheme.LABEL_COLORED);

		b_crearRol.addStyleName(ValoTheme.BUTTON_FRIENDLY);
		b_editarRol.addStyleName(ValoTheme.BUTTON_PRIMARY);

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);

		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");

		// l_titulo
		l_titulo = new Label();
		l_titulo.setStyleName("mih2");
		l_titulo.setImmediate(false);
		l_titulo.setWidth("100.0%");
		l_titulo.setHeight("-1px");
		l_titulo.setValue("Titulo");
		mainLayout.addComponent(l_titulo);

		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1);

		// l_permisos
		l_permisos = new Label();
		l_permisos.setStyleName("mih2");
		l_permisos.setImmediate(false);
		l_permisos.setWidth("100.0%");
		l_permisos.setHeight("-1px");
		l_permisos.setValue("Permisos");
		mainLayout.addComponent(l_permisos);

		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);

		// b_crearRol
		b_crearRol = new Button();
		b_crearRol.setCaption("Crear");
		b_crearRol.setImmediate(true);
		b_crearRol.setWidth("-1px");
		b_crearRol.setHeight("-1px");
		mainLayout.addComponent(b_crearRol);
		mainLayout.setComponentAlignment(b_crearRol, new Alignment(48));

		// b_editarRol
		b_editarRol = new Button();
		b_editarRol.setCaption("Editar");
		b_editarRol.setImmediate(true);
		b_editarRol.setWidth("-1px");
		b_editarRol.setHeight("-1px");
		mainLayout.addComponent(b_editarRol);
		mainLayout.setComponentAlignment(b_editarRol, new Alignment(48));

		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setColumns(2);
		gridLayout_1.setRows(3);

		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Nombre Rol");
		gridLayout_1.addComponent(label_3, 0, 0);

		// textField_1
		tf_nombreRol = new TextField();
		tf_nombreRol.setImmediate(false);
		tf_nombreRol.setWidth("100.0%");
		tf_nombreRol.setHeight("-1px");
		gridLayout_1.addComponent(tf_nombreRol, 1, 0);

		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Descripción");
		gridLayout_1.addComponent(label_2, 0, 1);

		// textArea_1
		ta_descripcion = new TextArea();
		ta_descripcion.setImmediate(false);
		ta_descripcion.setWidth("100.0%");
		ta_descripcion.setHeight("-1px");
		gridLayout_1.addComponent(ta_descripcion, 1, 1);

		return gridLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);

		// panel_1
		panel_1 = buildPanel_1();
		horizontalLayout_1.addComponent(panel_1);

		// panel_3
		panel_3 = buildPanel_3();
		horizontalLayout_1.addComponent(panel_3);

		return horizontalLayout_1;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setCaption("Acceso");
		panel_1.setImmediate(false);
		panel_1.setWidth("250px");
		panel_1.setHeight("-1px");

		// vl_acceso
		vl_acceso = new VerticalLayout();
		vl_acceso.setImmediate(false);
		vl_acceso.setWidth("100.0%");
		vl_acceso.setHeight("100.0%");
		vl_acceso.setMargin(false);
		panel_1.setContent(vl_acceso);

		return panel_1;
	}

	@AutoGenerated
	private Panel buildPanel_3() {
		// common part: create layout
		panel_3 = new Panel();
		panel_3.setCaption("General");
		panel_3.setImmediate(false);
		panel_3.setWidth("250px");
		panel_3.setHeight("-1px");

		// vl_general
		vl_general = new VerticalLayout();
		vl_general.setImmediate(false);
		vl_general.setWidth("100.0%");
		vl_general.setHeight("100.0%");
		vl_general.setMargin(false);
		panel_3.setContent(vl_general);

		return panel_3;
	}

}
