package com.ud.audiolearning.administracion.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

public class ViewDetalleDenuncia extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button b_resolver;
	@AutoGenerated
	private TextArea ta_observaciones;
	@AutoGenerated
	private Table table_reportesDenuncia;
	@AutoGenerated
	private Label l_titulo;
	public ViewDetalleDenuncia() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// l_titulo
		l_titulo = new Label();
		l_titulo.setStyleName("mih2");
		l_titulo.setImmediate(false);
		l_titulo.setWidth("-1px");
		l_titulo.setHeight("-1px");
		l_titulo.setValue("Detalles de la Denuncia");
		mainLayout.addComponent(l_titulo);
		
		// table_reportesDenuncia
		table_reportesDenuncia = new Table();
		table_reportesDenuncia.setCaption("Reportes de Denuncia");
		table_reportesDenuncia.setImmediate(false);
		table_reportesDenuncia.setWidth("100.0%");
		table_reportesDenuncia.setHeight("250px");
		mainLayout.addComponent(table_reportesDenuncia);
		
		// ta_observaciones
		ta_observaciones = new TextArea();
		ta_observaciones.setCaption("Observaciones");
		ta_observaciones.setImmediate(false);
		ta_observaciones.setWidth("100.0%");
		ta_observaciones.setHeight("-1px");
		mainLayout.addComponent(ta_observaciones);
		
		// b_resolver
		b_resolver = new Button();
		b_resolver.setCaption("Resolver Denuncia");
		b_resolver.setImmediate(false);
		b_resolver.setWidth("-1px");
		b_resolver.setHeight("-1px");
		mainLayout.addComponent(b_resolver);
		
		return mainLayout;
	}

}
