package com.ud.audiolearning.administracion.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class ViewCategoria extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button b_editarCategoria;
	@AutoGenerated
	private Button b_crearCategoria;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private TextArea textArea_1;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private TextField textField_2;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Label l_titulo;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ViewCategoria() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		iniciarImputs();
	}

	
	
	private void iniciarImputs() {

		Embedded imagen = new Embedded();
		imagen.setHeight("128px");
		imagen.setWidth("128px");
		imagen.setSource(new ThemeResource("img/categoria-icon.png"));
		horizontalLayout_1.addComponent(imagen, 0);
		horizontalLayout_1.setComponentAlignment(imagen, Alignment.MIDDLE_CENTER);

		

	}

	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// l_titulo
		l_titulo = new Label();
		l_titulo.setImmediate(false);
		l_titulo.setWidth("-1px");
		l_titulo.setHeight("-1px");
		l_titulo.setValue("Label");
		mainLayout.addComponent(l_titulo);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// b_crearCategoria
		b_crearCategoria = new Button();
		b_crearCategoria.setCaption("Crear");
		b_crearCategoria.setImmediate(false);
		b_crearCategoria.setWidth("-1px");
		b_crearCategoria.setHeight("-1px");
		mainLayout.addComponent(b_crearCategoria);
		mainLayout.setComponentAlignment(b_crearCategoria, new Alignment(48));
		
		// b_editarCategoria
		b_editarCategoria = new Button();
		b_editarCategoria.setCaption("Editar");
		b_editarCategoria.setImmediate(false);
		b_editarCategoria.setWidth("-1px");
		b_editarCategoria.setHeight("-1px");
		mainLayout.addComponent(b_editarCategoria);
		mainLayout.setComponentAlignment(b_editarCategoria, new Alignment(48));
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		horizontalLayout_1.addComponent(gridLayout_1);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("-1px");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setColumns(2);
		gridLayout_1.setRows(3);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Codigo");
		gridLayout_1.addComponent(label_2, 0, 0);
		
		// textField_2
		textField_2 = new TextField();
		textField_2.setImmediate(false);
		textField_2.setWidth("250px");
		textField_2.setHeight("-1px");
		gridLayout_1.addComponent(textField_2, 1, 0);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Nombre Categoria");
		gridLayout_1.addComponent(label_1, 0, 1);
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("250px");
		textField_1.setHeight("-1px");
		gridLayout_1.addComponent(textField_1, 1, 1);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Descripcion");
		gridLayout_1.addComponent(label_3, 0, 2);
		
		// textArea_1
		textArea_1 = new TextArea();
		textArea_1.setImmediate(false);
		textArea_1.setWidth("250px");
		textArea_1.setHeight("-1px");
		gridLayout_1.addComponent(textArea_1, 1, 2);
		
		return gridLayout_1;
	}

}
