package com.ud.audiolearning.api.ui;

import java.io.InputStream;
import java.io.Serializable;
import com.mongodb.gridfs.GridFSDBFile;
import com.ud.audiolearning.api.service.IBusquedasService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ErrorHandler;
import com.vaadin.server.FileDownloader;
import com.vaadin.server.StreamResource;
import com.vaadin.server.ThemeResource;
import com.vaadin.server.StreamResource.StreamSource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

public class windowDescargar extends CustomComponent implements Serializable{

	


	private static final long serialVersionUID = 1L;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button b_iniciarDescarga;
	@AutoGenerated
	private VerticalLayout vl_imagen;
	private IBusquedasService busquedaService;

	public windowDescargar(String id, IBusquedasService busquedasService) {
		this.busquedaService = busquedasService;

		buildMainLayout();
		setCompositionRoot(mainLayout);
		GridFSDBFile audioFile = busquedaService.buscarAudioFile(id);
		
		b_iniciarDescarga.addStyleName(ValoTheme.BUTTON_PRIMARY);
		
		Embedded imagen = new Embedded();
		imagen.setSource(new ThemeResource("img/downloadIcon.png"));
		
		vl_imagen.addComponent(imagen);

		if (audioFile != null) {
				StreamResource resource = new StreamResource(new StreamSource() {
					
					private static final long serialVersionUID = 1L;

					@Override
					public InputStream getStream() {

						return audioFile.getInputStream();
					}
				}, audioFile.getFilename());

				FileDownloader fileDownloader = new FileDownloader(resource);
				fileDownloader.extend(b_iniciarDescarga);
				fileDownloader.setErrorHandler(new ErrorHandler() {
					
					private static final long serialVersionUID = 1L;

					@Override
					public void error(com.vaadin.server.ErrorEvent event) {
					System.err.println("Archivo para guardar null");
					}
				});

		
		}

	}

	

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// vl_imagen
		vl_imagen = new VerticalLayout();
		vl_imagen.setImmediate(false);
		vl_imagen.setWidth("-1px");
		vl_imagen.setHeight("-1px");
		vl_imagen.setMargin(false);
		mainLayout.addComponent(vl_imagen);
		mainLayout.setComponentAlignment(vl_imagen, new Alignment(48));
		
		// b_iniciarDescarga
		b_iniciarDescarga = new Button();
		b_iniciarDescarga.setCaption("Iniciar Descarga");
		b_iniciarDescarga.setImmediate(true);
		b_iniciarDescarga.setWidth("-1px");
		b_iniciarDescarga.setHeight("-1px");
		mainLayout.addComponent(b_iniciarDescarga);
		
		return mainLayout;
	}

}
