package com.ud.audiolearning.mislistas.ui;

import java.text.SimpleDateFormat;

import org.springframework.beans.factory.annotation.Autowired;
import org.vaadin.teemu.VaadinIcons;

import com.ud.audiolearning.api.anotaciones.UIComponent;
import com.ud.audiolearning.api.interfaces.AudioLearnUI;
import com.ud.audiolearning.api.domain.ListaDifusion;
import com.ud.audiolearning.api.ui.LayoutCellDescripcion;
import com.ud.audiolearning.mislistas.service.MisListasService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.ExternalResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

import ru.xpoft.vaadin.VaadinView;

@SuppressWarnings("serial")
@UIComponent
@VaadinView("listasReproduccion")
public class ListasReproduccion extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table table_listasReproduccion;
	@AutoGenerated
	private HorizontalLayout hl_cabecera;
	@AutoGenerated
	private Button b_addLista;
	@AutoGenerated
	private Label l_titulo;
	@Autowired
	MisListasService misListasService;

	private BeanItemContainer<ListaDifusion> BICListasReproduccion;

	SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd hh:mm");
	
	
	public ListasReproduccion() {

	}

	@Override
	public void enter(ViewChangeEvent event) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		init();
		style();
	}

	
	private void init(){
		
		b_addLista.addClickListener(e -> addListaDifusion(e));
		BICListasReproduccion = new BeanItemContainer<ListaDifusion>(ListaDifusion.class);
		table_listasReproduccion.setContainerDataSource(BICListasReproduccion);
		table_listasReproduccion.addGeneratedColumn("Imagen", this::construirImagen);
		table_listasReproduccion.addGeneratedColumn("Descripcion", this::construirDescripcion);
		table_listasReproduccion.addGeneratedColumn("Audios", this::construirAudios);
		table_listasReproduccion.addGeneratedColumn("Admin", this::construirAdmin);
		table_listasReproduccion.setVisibleColumns("Imagen", "Descripcion", "Audios", "Admin");
		table_listasReproduccion.setColumnWidth("Imagen", 110);
		table_listasReproduccion.setColumnWidth("Descripcion", 500);
		//t_listasDifusion.setColumnWidth("Admin", 170);

		AudioLearnUI ui = (AudioLearnUI) UI.getCurrent();
		ui.getPrivateUI().getAreaContenido().setHeight("100%");
		llenar(null);
		
		
	}
	
	private void llenar(String string) {

		BICListasReproduccion.removeAllItems();
		BICListasReproduccion.addAll(misListasService.findAllListasDifusion());

	}
	
	private Object construirImagen(Table source, Object itemId, Object columnId) {
		//ListaDifusion lista = (ListaDifusion) itemId;
		Embedded embedded = new Embedded();
		embedded.setSource(new ExternalResource(
				"http://icons.iconarchive.com/icons/webalys/kameleon.pics/72/Music-Equalizer-icon.png"));
		VerticalLayout vl = new VerticalLayout();
		
	
		vl.addComponents(embedded);
		vl.setComponentAlignment(embedded, Alignment.MIDDLE_CENTER);
		vl.setWidth("100%");
		return vl;
	}
	private Object construirDescripcion(Table source, Object itemId, Object columnId) {
		ListaDifusion lista = (ListaDifusion) itemId;
		return new LayoutCellDescripcion(lista.getTitulo(), lista.getDescripcion(), lista.getFechaCreacion(),
				lista.getEstado());
	}

	private Object construirAudios(Table source, Object itemId, Object columnId) {
		ListaDifusion lista = (ListaDifusion) itemId;
		VerticalLayout vl = new VerticalLayout();
		Label numAdios = new Label("" + lista.getAudios().size());
		Label audios = new Label("Audios");
		numAdios.setWidth("-1px");
		audios.setWidth("-1px");
		numAdios.addStyleName(ValoTheme.LABEL_COLORED);
		numAdios.addStyleName("labelSizeAudios");
		numAdios.addStyleName(ValoTheme.LABEL_BOLD);
		audios.addStyleName(ValoTheme.LABEL_COLORED);
		audios.addStyleName(ValoTheme.LABEL_H3);
		audios.addStyleName(ValoTheme.LABEL_BOLD);
		vl.addComponents(numAdios, audios);
		vl.setComponentAlignment(numAdios, Alignment.MIDDLE_CENTER);
		vl.setComponentAlignment(audios, Alignment.MIDDLE_CENTER);

		return vl;
	}

	private Object construirAdmin(Table source, Object itemId, Object columnId) {
		ListaDifusion lista = (ListaDifusion) itemId;
		VerticalLayout vl = new VerticalLayout();
		HorizontalLayout hl = new HorizontalLayout();
		Button editar = new Button("Editar Lista");
		editar.addStyleName("buttonEdit");
		editar.addClickListener(e -> editarLista(lista));
		editar.setIcon(VaadinIcons.EDIT);
		editar.addStyleName(ValoTheme.BUTTON_BORDERLESS_COLORED);
		editar.addStyleName(ValoTheme.BUTTON_ICON_ALIGN_TOP);
		Button eliminar = new Button("Eliminar Lista");
		eliminar.addStyleName("buttonRemove");
		eliminar.addClickListener(e -> eliminarLista(lista));
		eliminar.setIcon(VaadinIcons.TRASH);
		eliminar.addStyleName(ValoTheme.BUTTON_BORDERLESS_COLORED);
		eliminar.addStyleName(ValoTheme.BUTTON_ICON_ALIGN_TOP);
		
		hl.setStyleName("adminMisaudios");
		hl.addComponents(editar, eliminar);
		vl.setWidth("100%");
		vl.addComponent(hl);
		vl.setComponentAlignment(hl, Alignment.MIDDLE_CENTER);
		return vl;
	}
	
//	private void addAudioLista(ListaDifusion lista) {
////		Window w = new Window("Editar Lista");
////		w.setContent(new ViewAddAudio());
////		w.setModal(true);
////		w.center();
////		w.setWidth("-1px");
////		w.setHeight("-1px");
////		UI.getCurrent().addWindow(w);
//	}
	
	private void addListaDifusion(ClickEvent e) {

//		Window w = new Window("Crear Lista");
//		w.setContent(new ViewInfoLista(new ListaDifusion(), "C", misListasService, this::llenar));
//		w.setModal(true);
//		w.center();
//		w.setWidth("500px");
//		w.setHeight("-1px");
//		UI.getCurrent().addWindow(w);

	}
	
	private void eliminarLista(ListaDifusion lista) {

//		ConfirmDialog.show(UI.getCurrent(), "Eliminar Lista de Difusion:",
//				"Esta seguro que desea eliminar la lista de reproduccion " + lista.getTitulo(), "Estoy Seguro", "No",
//				new ConfirmDialog.Listener() {
//
//					public void onClose(ConfirmDialog dialog) {
//						if (dialog.isConfirmed()) {
//							misListasService.eliminarListaDifusion(lista);
//							llenar(null);
//						} else {
//						}
//					}
//				});
	}

	private void editarLista(ListaDifusion listaReproduccion) {
//		Window w = new Window("Editar Lista");
//		w.setContent(new ViewInfoLista(listaReproduccion, "U", misListasService, this::llenar));
//		w.setModal(true);
//		w.center();
//		w.setWidth("500px");
//		w.setHeight("-1px");
//		UI.getCurrent().addWindow(w);

	}
	
	
	private void style(){
		
		l_titulo.addStyleName(ValoTheme.LABEL_COLORED);
		l_titulo.addStyleName(ValoTheme.LABEL_H2);
		l_titulo.addStyleName(ValoTheme.LABEL_BOLD);
		

		b_addLista.setIcon(VaadinIcons.PLUS);
		b_addLista.addStyleName(ValoTheme.BUTTON_PRIMARY);
		table_listasReproduccion.addStyleName(ValoTheme.TABLE_NO_HEADER);
		table_listasReproduccion.addStyleName(ValoTheme.TABLE_NO_VERTICAL_LINES);
		table_listasReproduccion.addStyleName(ValoTheme.TABLE_BORDERLESS);
	}
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setStyleName("contenido");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("1005px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("1005px");
		
		// hl_cabecera
		hl_cabecera = buildHl_cabecera();
		mainLayout.addComponent(hl_cabecera);
		
		// table_1
		table_listasReproduccion = new Table();
		table_listasReproduccion.setImmediate(false);
		table_listasReproduccion.setWidth("100.0%");
		table_listasReproduccion.setHeight("100.0%");
		mainLayout.addComponent(table_listasReproduccion);
		mainLayout.setExpandRatio(table_listasReproduccion, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHl_cabecera() {
		// common part: create layout
		hl_cabecera = new HorizontalLayout();
		hl_cabecera.setStyleName("cabeceraContenido");
		hl_cabecera.setImmediate(false);
		hl_cabecera.setWidth("100.0%");
		hl_cabecera.setHeight("-1px");
		hl_cabecera.setMargin(false);
		
		// l_titulo
		l_titulo = new Label();
		l_titulo.setImmediate(false);
		l_titulo.setWidth("-1px");
		l_titulo.setHeight("-1px");
		l_titulo.setValue("Listas de Reproducción");
		hl_cabecera.addComponent(l_titulo);
		
		// b_addLista
		b_addLista = new Button();
		b_addLista.setCaption("Agregar Lista");
		b_addLista.setImmediate(false);
		b_addLista.setWidth("-1px");
		b_addLista.setHeight("-1px");
		hl_cabecera.addComponent(b_addLista);
		hl_cabecera.setComponentAlignment(b_addLista, new Alignment(6));
		
		return hl_cabecera;
	}

}
