package com.ud.audiolearning.reproductor.ui;

import org.vaadin.teemu.VaadinIcons;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

@SuppressWarnings("serial")
public class ViewCalificacion extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button b_calificar;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private VerticalLayout vl_contenido;
	@AutoGenerated
	private GridLayout gridLayout_3;
	@AutoGenerated
	private OptionGroup op_util;
	@AutoGenerated
	private Label label_7;
	@AutoGenerated
	private OptionGroup op_original;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private OptionGroup op_claridad;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private OptionGroup op_interesante;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private OptionGroup op_bienCate;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label l_contenido;
	@AutoGenerated
	private VerticalLayout vl_aporteCalidad;
	@AutoGenerated
	private GridLayout gridLayout_7;
	@AutoGenerated
	private Label label_10;
	@AutoGenerated
	private OptionGroup op_tema;
	@AutoGenerated
	private Label label_11;
	@AutoGenerated
	private OptionGroup op_grabacion;
	@AutoGenerated
	private Label label_12;
	@AutoGenerated
	private OptionGroup op_profesional;
	@AutoGenerated
	private Label label_13;
	@AutoGenerated
	private OptionGroup op_personal;
	@AutoGenerated
	private Label label_8;
	@AutoGenerated
	private Label l_aporteCalidad;
	@AutoGenerated
	private Label l_subtitulo;
	@AutoGenerated
	private Label l_titulo;
	public ViewCalificacion() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		init();
		style();
	}

	private void style() {

		l_titulo.addStyleName(ValoTheme.LABEL_H2);
		l_titulo.addStyleName(ValoTheme.LABEL_COLORED);
		l_titulo.addStyleName(ValoTheme.LABEL_BOLD);
		l_titulo.addStyleName("mih2");
		l_subtitulo.addStyleName(ValoTheme.LABEL_H3);
		
		
		l_aporteCalidad.addStyleName(ValoTheme.LABEL_COLORED);
		l_aporteCalidad.addStyleName(ValoTheme.LABEL_H3);
		
		l_contenido.addStyleName(ValoTheme.LABEL_COLORED);
		l_contenido.addStyleName(ValoTheme.LABEL_H3);
		
		vl_aporteCalidad.addStyleName(ValoTheme.LAYOUT_CARD);
		vl_aporteCalidad.setMargin(new MarginInfo(false, true, true, true));
		
		vl_contenido.addStyleName(ValoTheme.LAYOUT_CARD);
		vl_contenido.setMargin(new MarginInfo(false, true, true, true));
		
		b_calificar.addStyleName(ValoTheme.BUTTON_PRIMARY);

	}

	private void init() {
		
		llenarOptionGroups();
	}

	public void llenarOptionGroups() {

		op_profesional.addItem(true);
		op_profesional.addItem(false);
		op_profesional.setItemIcon(true, VaadinIcons.THUMBS_UP_O);
		op_profesional.setItemIcon(false, VaadinIcons.THUMBS_DOWN);
		op_profesional.setItemCaption(true, "");
		op_profesional.setItemCaption(false, "");
		op_profesional.addStyleName(ValoTheme.OPTIONGROUP_HORIZONTAL);
		

		op_personal.addItem(true);
		op_personal.addItem(false);
		op_personal.setItemIcon(true, VaadinIcons.THUMBS_UP_O);
		op_personal.setItemIcon(false, VaadinIcons.THUMBS_DOWN);
		op_personal.setItemCaption(true, "");
		op_personal.setItemCaption(false, "");
		op_personal.addStyleName(ValoTheme.OPTIONGROUP_HORIZONTAL);

		op_grabacion.addItem(true);
		op_grabacion.addItem(false);
		op_grabacion.setItemIcon(true, VaadinIcons.THUMBS_UP_O);
		op_grabacion.setItemIcon(false, VaadinIcons.THUMBS_DOWN);
		op_grabacion.setItemCaption(true, "");
		op_grabacion.setItemCaption(false, "");
		op_grabacion.addStyleName(ValoTheme.OPTIONGROUP_HORIZONTAL);

		op_tema.addItem(true);
		op_tema.addItem(false);
		op_tema.setItemIcon(true, VaadinIcons.THUMBS_UP_O);
		op_tema.setItemIcon(false, VaadinIcons.THUMBS_DOWN);
		op_tema.setItemCaption(true, "");
		op_tema.setItemCaption(false, "");
		op_tema.addStyleName(ValoTheme.OPTIONGROUP_HORIZONTAL);

		op_util.addItem(true);
		op_util.addItem(false);
		op_util.setItemIcon(true, VaadinIcons.THUMBS_UP_O);
		op_util.setItemIcon(false, VaadinIcons.THUMBS_DOWN);
		op_util.setItemCaption(true, "");
		op_util.setItemCaption(false, "");
		op_util.addStyleName(ValoTheme.OPTIONGROUP_HORIZONTAL);

		op_interesante.addItem(true);
		op_interesante.addItem(false);
		op_interesante.setItemIcon(true, VaadinIcons.THUMBS_UP_O);
		op_interesante.setItemIcon(false, VaadinIcons.THUMBS_DOWN);
		op_interesante.setItemCaption(true, "");
		op_interesante.setItemCaption(false, "");
		op_interesante.addStyleName(ValoTheme.OPTIONGROUP_HORIZONTAL);

		op_original.addItem(true);
		op_original.addItem(false);
		op_original.setItemIcon(true, VaadinIcons.THUMBS_UP_O);
		op_original.setItemIcon(false, VaadinIcons.THUMBS_DOWN);
		op_original.setItemCaption(true, "");
		op_original.setItemCaption(false, "");
		op_original.addStyleName(ValoTheme.OPTIONGROUP_HORIZONTAL);

		op_claridad.addItem(true);
		op_claridad.addItem(false);
		op_claridad.setItemIcon(true, VaadinIcons.THUMBS_UP_O);
		op_claridad.setItemIcon(false, VaadinIcons.THUMBS_DOWN);
		op_claridad.setItemCaption(true, "");
		op_claridad.setItemCaption(false, "");
		op_claridad.addStyleName(ValoTheme.OPTIONGROUP_HORIZONTAL);

		op_bienCate.addItem(true);
		op_bienCate.addItem(false);
		op_bienCate.setItemIcon(true, VaadinIcons.THUMBS_UP_O);
		op_bienCate.setItemIcon(false, VaadinIcons.THUMBS_DOWN);
		op_bienCate.setItemCaption(true, "");
		op_bienCate.setItemCaption(false, "");
		op_bienCate.addStyleName(ValoTheme.OPTIONGROUP_HORIZONTAL);

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// l_titulo
		l_titulo = new Label();
		l_titulo.setImmediate(false);
		l_titulo.setWidth("-1px");
		l_titulo.setHeight("-1px");
		l_titulo.setValue("Gracias por tu Calificación!");
		mainLayout.addComponent(l_titulo);
		
		// l_subtitulo
		l_subtitulo = new Label();
		l_subtitulo.setImmediate(false);
		l_subtitulo.setWidth("100.0%");
		l_subtitulo.setHeight("-1px");
		l_subtitulo.setValue(
				"Tu opinión sobre de este audio es muy importante para nosotros y permitira a nuestra comunidad seguir creciendo, valoramos lo que piensas.");
		mainLayout.addComponent(l_subtitulo);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		mainLayout.setComponentAlignment(horizontalLayout_1, new Alignment(20));
		
		// b_calificar
		b_calificar = new Button();
		b_calificar.setCaption("Enviar Calificación");
		b_calificar.setImmediate(true);
		b_calificar.setWidth("-1px");
		b_calificar.setHeight("-1px");
		mainLayout.addComponent(b_calificar);
		mainLayout.setComponentAlignment(b_calificar, new Alignment(48));
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// vl_aporteCalidad
		vl_aporteCalidad = buildVl_aporteCalidad();
		horizontalLayout_1.addComponent(vl_aporteCalidad);
		horizontalLayout_1.setComponentAlignment(vl_aporteCalidad, new Alignment(20));
		
		// vl_contenido
		vl_contenido = buildVl_contenido();
		horizontalLayout_1.addComponent(vl_contenido);
		horizontalLayout_1.setComponentAlignment(vl_contenido, new Alignment(20));
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVl_aporteCalidad() {
		// common part: create layout
		vl_aporteCalidad = new VerticalLayout();
		vl_aporteCalidad.setImmediate(false);
		vl_aporteCalidad.setWidth("-1px");
		vl_aporteCalidad.setHeight("-1px");
		vl_aporteCalidad.setMargin(false);
		vl_aporteCalidad.setSpacing(true);
		
		// l_aporteCalidad
		l_aporteCalidad = new Label();
		l_aporteCalidad.setImmediate(false);
		l_aporteCalidad.setWidth("-1px");
		l_aporteCalidad.setHeight("-1px");
		l_aporteCalidad.setValue("Aporte y Calidad");
		vl_aporteCalidad.addComponent(l_aporteCalidad);
		vl_aporteCalidad.setComponentAlignment(l_aporteCalidad, new Alignment(48));
		
		// gridLayout_7
		gridLayout_7 = buildGridLayout_7();
		vl_aporteCalidad.addComponent(gridLayout_7);
		
		return vl_aporteCalidad;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_7() {
		// common part: create layout
		gridLayout_7 = new GridLayout();
		gridLayout_7.setImmediate(false);
		gridLayout_7.setWidth("-1px");
		gridLayout_7.setHeight("-1px");
		gridLayout_7.setMargin(false);
		gridLayout_7.setSpacing(true);
		gridLayout_7.setColumns(2);
		gridLayout_7.setRows(5);
		
		// label_8
		label_8 = new Label();
		label_8.setImmediate(false);
		label_8.setWidth("-1px");
		label_8.setHeight("-1px");
		label_8.setValue("Aporte Personal");
		gridLayout_7.addComponent(label_8, 0, 0);
		
		// op_personal
		op_personal = new OptionGroup();
		op_personal.setImmediate(false);
		op_personal.setWidth("-1px");
		op_personal.setHeight("30px");
		gridLayout_7.addComponent(op_personal, 1, 0);
		
		// label_13
		label_13 = new Label();
		label_13.setImmediate(false);
		label_13.setWidth("-1px");
		label_13.setHeight("-1px");
		label_13.setValue("Aporte Profesional");
		gridLayout_7.addComponent(label_13, 0, 1);
		
		// op_profesional
		op_profesional = new OptionGroup();
		op_profesional.setImmediate(false);
		op_profesional.setWidth("-1px");
		op_profesional.setHeight("30px");
		gridLayout_7.addComponent(op_profesional, 1, 1);
		
		// label_12
		label_12 = new Label();
		label_12.setImmediate(false);
		label_12.setWidth("-1px");
		label_12.setHeight("-1px");
		label_12.setValue("Calidad de Grabación");
		gridLayout_7.addComponent(label_12, 0, 2);
		
		// op_grabacion
		op_grabacion = new OptionGroup();
		op_grabacion.setImmediate(false);
		op_grabacion.setWidth("-1px");
		op_grabacion.setHeight("30px");
		gridLayout_7.addComponent(op_grabacion, 1, 2);
		
		// label_11
		label_11 = new Label();
		label_11.setImmediate(false);
		label_11.setWidth("-1px");
		label_11.setHeight("-1px");
		label_11.setValue("Calidad de Contenido");
		gridLayout_7.addComponent(label_11, 0, 3);
		
		// op_tema
		op_tema = new OptionGroup();
		op_tema.setImmediate(false);
		op_tema.setWidth("-1px");
		op_tema.setHeight("30px");
		gridLayout_7.addComponent(op_tema, 1, 3);
		
		// label_10
		label_10 = new Label();
		label_10.setImmediate(false);
		label_10.setWidth("-1px");
		label_10.setHeight("30px");
		label_10.setValue(".");
		gridLayout_7.addComponent(label_10, 0, 4);
		
		return gridLayout_7;
	}

	@AutoGenerated
	private VerticalLayout buildVl_contenido() {
		// common part: create layout
		vl_contenido = new VerticalLayout();
		vl_contenido.setImmediate(false);
		vl_contenido.setWidth("-1px");
		vl_contenido.setHeight("-1px");
		vl_contenido.setMargin(false);
		vl_contenido.setSpacing(true);
		
		// l_contenido
		l_contenido = new Label();
		l_contenido.setImmediate(false);
		l_contenido.setWidth("-1px");
		l_contenido.setHeight("-1px");
		l_contenido.setValue("Contenido");
		vl_contenido.addComponent(l_contenido);
		vl_contenido.setComponentAlignment(l_contenido, new Alignment(48));
		
		// gridLayout_3
		gridLayout_3 = buildGridLayout_3();
		vl_contenido.addComponent(gridLayout_3);
		
		return vl_contenido;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_3() {
		// common part: create layout
		gridLayout_3 = new GridLayout();
		gridLayout_3.setImmediate(false);
		gridLayout_3.setWidth("-1px");
		gridLayout_3.setHeight("-1px");
		gridLayout_3.setMargin(false);
		gridLayout_3.setSpacing(true);
		gridLayout_3.setColumns(2);
		gridLayout_3.setRows(5);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Bien Categorizado");
		gridLayout_3.addComponent(label_3, 0, 0);
		
		// op_bienCate
		op_bienCate = new OptionGroup();
		op_bienCate.setImmediate(false);
		op_bienCate.setWidth("-1px");
		op_bienCate.setHeight("30px");
		gridLayout_3.addComponent(op_bienCate, 1, 0);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Interesante");
		gridLayout_3.addComponent(label_1, 0, 1);
		
		// op_interesante
		op_interesante = new OptionGroup();
		op_interesante.setImmediate(false);
		op_interesante.setWidth("-1px");
		op_interesante.setHeight("30px");
		gridLayout_3.addComponent(op_interesante, 1, 1);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Claro");
		gridLayout_3.addComponent(label_2, 0, 2);
		
		// op_claridad
		op_claridad = new OptionGroup();
		op_claridad.setImmediate(false);
		op_claridad.setWidth("-1px");
		op_claridad.setHeight("30px");
		gridLayout_3.addComponent(op_claridad, 1, 2);
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Originalidad");
		gridLayout_3.addComponent(label_4, 0, 3);
		
		// op_original
		op_original = new OptionGroup();
		op_original.setImmediate(false);
		op_original.setWidth("-1px");
		op_original.setHeight("30px");
		gridLayout_3.addComponent(op_original, 1, 3);
		
		// label_7
		label_7 = new Label();
		label_7.setImmediate(false);
		label_7.setWidth("-1px");
		label_7.setHeight("-1px");
		label_7.setValue("Utilidad");
		gridLayout_3.addComponent(label_7, 0, 4);
		
		// op_util
		op_util = new OptionGroup();
		op_util.setImmediate(false);
		op_util.setWidth("-1px");
		op_util.setHeight("30px");
		gridLayout_3.addComponent(op_util, 1, 4);
		
		return gridLayout_3;
	}

}
