package com.ud.audiolearning.reproductor.ui;

import java.util.Date;

import org.bson.types.ObjectId;

import com.ud.audiolearning.api.domain.Audio;
import com.ud.audiolearning.api.domain.ReporteDenuncia;
import com.ud.audiolearning.api.domain.Usuario;
import com.ud.audiolearning.api.ui.AppSession;
import com.ud.audiolearning.reproductor.service.ReproductorService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup.CommitException;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

@SuppressWarnings("serial")
public class ViewDenuncia extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button b_reportar;
	@AutoGenerated
	private TextArea ta_detalleDenuncia;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private OptionGroup optionGroup_1;
	@AutoGenerated
	private Label l_mensaje;
	@AutoGenerated
	private Label l_titulo;
	private ReproductorService reproductorService;

	private ReporteDenuncia reporteDenuncia;

	FieldGroup fieldGroup;
	private Audio audio;

	public ViewDenuncia(ReproductorService reproductorService, Audio audio) {

		this.audio = audio;

		this.reproductorService = reproductorService;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		style();
		this.reporteDenuncia = new ReporteDenuncia();
		this.reporteDenuncia.setFechaDenuncia(new Date());
		Usuario usuarioDenuncia = new Usuario();
		usuarioDenuncia.setNick(AppSession.getUser().getNick());
		usuarioDenuncia.setId(AppSession.getUser().getId());
		this.reporteDenuncia.setUsuario(usuarioDenuncia);

		BeanItem<ReporteDenuncia> BeanReporte = new BeanItem<ReporteDenuncia>(this.reporteDenuncia);
		fieldGroup = new FieldGroup();

		fieldGroup.setItemDataSource(BeanReporte);
		fieldGroup.bind(ta_detalleDenuncia, "detalle");
		fieldGroup.bind(optionGroup_1, "motivo");
		b_reportar.addClickListener(e -> enviarReporte());

		ta_detalleDenuncia.setNullRepresentation("");

		cargarTiposDenuncia();
	}

	private void enviarReporte() {

		try {

			if (optionGroup_1.getValue() == null) {

				
				throw new Error("Debe seleccionar al menos un tipo de  denuncia");

			}

			fieldGroup.commit();

			reproductorService.enviarDenuncia(this.audio, this.reporteDenuncia);

			UI.getCurrent().getWindows().forEach(window -> window.close());
			
			Notification n = new Notification("Correcto!", "Se ha enviado correctamente el reporte",	Type.HUMANIZED_MESSAGE);
			n.setDelayMsec(3600);
			n.show(UI.getCurrent().getPage());

		} catch (CommitException e) {
			Notification.show("Error!", "Se produjo un error al intentar validad los datos del reporte de Denuncia",
					Type.ERROR_MESSAGE);
			e.printStackTrace();
		} catch (Error error) {
			Notification.show("Aviso de validación!", error.getMessage(), Type.ERROR_MESSAGE);
		}

	}

	private void cargarTiposDenuncia() {
		reproductorService.buscarTiposDenincia().forEach(tipo -> {
			optionGroup_1.addItem(tipo.getCodigo());
			optionGroup_1.setItemCaption(tipo.getCodigo(), tipo.getNombre());
		});
	}

	private void style() {

		l_titulo.addStyleName("mih2");
		l_titulo.addStyleName(ValoTheme.LABEL_BOLD);
		l_titulo.addStyleName(ValoTheme.LABEL_H2);
		l_titulo.addStyleName(ValoTheme.LABEL_COLORED);

		b_reportar.addStyleName(ValoTheme.BUTTON_PRIMARY);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("500px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("500px");
		setHeight("-1px");

		// l_titulo
		l_titulo = new Label();
		l_titulo.setImmediate(false);
		l_titulo.setWidth("100.0%");
		l_titulo.setHeight("-1px");
		l_titulo.setValue("Reporte de Contenido Inadecuado");
		mainLayout.addComponent(l_titulo);

		// l_mensaje
		l_mensaje = new Label();
		l_mensaje.setImmediate(false);
		l_mensaje.setWidth("100.0%");
		l_mensaje.setHeight("-1px");
		l_mensaje.setValue(
				"Aqui podras reportar el contenido inapropiado que encuentres, este sera revisado y se tomaran las respectivas medidas del caso.");
		mainLayout.addComponent(l_mensaje);

		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);

		// ta_detalleDenuncia
		ta_detalleDenuncia = new TextArea();
		ta_detalleDenuncia.setCaption("Detalle");
		ta_detalleDenuncia.setImmediate(false);
		ta_detalleDenuncia.setWidth("100.0%");
		ta_detalleDenuncia.setHeight("-1px");
		mainLayout.addComponent(ta_detalleDenuncia);

		// b_reportar
		b_reportar = new Button();
		b_reportar.setCaption("Reportar");
		b_reportar.setImmediate(true);
		b_reportar.setWidth("-1px");
		b_reportar.setHeight("-1px");
		mainLayout.addComponent(b_reportar);
		mainLayout.setComponentAlignment(b_reportar, new Alignment(48));

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setCaption("Tipos de Denuncia");
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("200px");

		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);

		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(true);

		// optionGroup_1
		optionGroup_1 = new OptionGroup();
		optionGroup_1.setImmediate(false);
		optionGroup_1.setWidth("-1px");
		optionGroup_1.setHeight("-1px");
		verticalLayout_2.addComponent(optionGroup_1);

		return verticalLayout_2;
	}

}
